version: "3"
services:

    web:
        build: .
        image: "penguin:dev"
        command: "mix phoenix.server"
        ports:
            - "4000:4000"
        volumes:
            - ./:/code
        working_dir: /code
        links:
            - db

    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: docker
            POSTGRES_USER: docker
