version: "3"
services:

    web:
        image: "marcelocg/phoenix"
        command: "mix phoenix"
        ports:
            - "4000:4000"
        volumes:
            - ./phoenix:/code
        working_dir: /code
        links:
            - db

    db:
        image: "tcgerlach/sqlite"
        volumes:
            - ./sqlite:/data
        working_dir: /data